language: node_js
node_js:
  - "6"

jobs:  
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm test && npm run report-coverage
    - stage: Publish
      name: "Publish to npm"
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
