name: Build

on:
  push:
    branches: [ master, '*' ]
  pull_request:
    branches: [ master, '*' ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  Test:
    name: Unit Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter && ./cc-test-reporter before-build
      - run: npm test
        env: 
          CI: Github_Action
          TRAVIS: 1
      - run: ./cc-test-reporter after-build -t lcov

  Release:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: Test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run semantic-release
